apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: emmision-test
spec:
  hosts:
    - emmision-test
  http:
  - route:
    - destination:
        host: emmision-test
        subset: v1
      weight: 80
    - destination:
        host: emmision-test
        subset: v2
      weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: emmision-test
spec:
  host: emmision-test
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2


